# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc544d09b08e2ab241cdc6bbfb8cff9c9d38ef10495ed5cc52bf5fb41c9d92b136858d91e7a5d46f26d4b32f066c96b008423f5f442b9ae3219cffa63f0cc60

test:
  secret_key_base: 8d4bc0681b33b601d1b2782a0fb877617d5bb6a6da844824db4a68a6a80e7e1d3dcaafea09361a87733e800336232be7922bccc6072117d1f5362eeae5c4c803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
